site_name: Algoritmos y Programación II
site_dir: _site
site_url: "https://algoritmos-rw.github.io/algo2"
site_description: >
  Página de la materia Algoritmos y Programación II, curso Buchwald
  (ex Wachenchauzer). Facultad de Ingeniería, Universidad de Buenos Aires.
theme:
  name: material
  custom_dir: docs/_custom
  language: es
  palette:
    primary: blue
    accent: blue
  font:
    text: Rosario   # Probably pick a better font.
    code: Fira Mono
  favicon: img/favicon.ico
plugins:
  - git-authors
  - git-revision-date-localized
nav:
  - index.md
  - bibliografia.md
  - regimen.md
  - Apuntes:
      - Ordenamientos externos: apuntes/external-sorts.md
    # Eventualmente, se podría hacer introducir una subsección "Grafos" aquí.
    # - Grafos:
      - Random walks: apuntes/random_walks.md
      - Centralidad: apuntes/centralidad.md
      - PageRank: apuntes/pagerank.md
      - Label propagation: apuntes/label_propagation.md
      - Componentes fuertemente conexas: apuntes/cfc.md
      - apuntes/kml.md
    # TODO:
    # - Otros apuntes: material/apuntes.md
  - Preguntas frecuentes:
      - faq/general.md
      - faq/entorno.md
      - faq/primeros-pasos.md
      - faq/compilacion-ejecucion.md
      - faq/lenguaje-c.md
      - faq/valgrind.md
      - faq/tda.md
      - faq/cola.md
      - faq/lista-enlazada.md
      - faq/hash.md
      - faq/heap.md
      - faq/abb.md
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - codehilite:
      guess_lang: false
  - footnotes
  - meta
  - toc:
      permalink: true
      slugify: !!python/name:pymdownx.slugs.uslugify
  - smarty
  - pymdownx.arithmatex:
      preview: false
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shortener: true
  - pymdownx.mark
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.tilde
