site_name: Algoritmos y Programación II
site_dir: _site
site_url: "https://algoritmos-rw.github.io/algo2"
site_description: >
  Página de la materia Algoritmos y Programación II, curso Buchwald
  (ex Wachenchauzer). Facultad de Ingeniería, Universidad de Buenos Aires.
theme:
  name: material
  custom_dir: docs/_custom
  language: es
  palette:
    primary: blue
    accent: blue
  font:
    text: Rosario   # Probably pick a better font.
    code: Fira Mono
  favicon: img/favicon.ico
plugins:
  - git-authors
  - git-revision-date-localized
nav:
  - index.md
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - codehilite:
      guess_lang: false
  - footnotes
  - meta
  - toc:
      permalink: true
      slugify: !!python/name:pymdownx.slugs.uslugify
  - smarty
  - pymdownx.arithmatex:
      preview: false
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shortener: true
  - pymdownx.mark
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.tilde
